In [2]:
import numpy as np
from scipy import linalg

In [73]:
A = np.array([[1, 1, 1, 0, 0], 
     [-1, 1, 0, 1, 0],
     [1, -1, 0, 0, 1]])

b = np.array([[4], [2], [2]])

c = np.array([[-2], [4], [0], [0], [0]])

In [79]:
# iteration i = 1

i = 1
j = 2
p = 3
q = 4
k = 5

B = A[:, [i-1, j-1, k-1]]
B_inv = linalg.inv(B)
x_b = B_inv @ b
x_n = np.array([[0], [0]])
c_bar = c[p-1] - c[[i-1, j-1, k-1]].T @ B_inv @ A[:, p-1]
c_bar_2 = c[q-1] - c[[i-1, j-1, k-1]].T @ B_inv @ A[:, q-1]


print("B = ")
print(B)
print("\n B^-1 = ")
print(B_inv)
print("\n x_b")
print(x_b)
print("\n x_n")
print(x_n)
print("\n c_"+str(p)+"_bar = ")
print(c_bar)
print("\n c_"+str(q)+"_bar = ")
print(c_bar_2)

B = 
[[ 1  1  0]
 [-1  1  0]
 [ 1 -1  1]]

 B^-1 = 
[[ 0.5 -0.5 -0. ]
 [ 0.5  0.5 -0. ]
 [ 0.   1.   1. ]]

 x_b
[[1.]
 [3.]
 [4.]]

 x_n
[[0]
 [0]]

 c_3_bar = 
[-1.]

 c_4_bar = 
[-3.]


In [81]:
# x_3 enters the basis
d = -B_inv @ A[:, p-1]
values = [x_b[0]/ d[0], x_b[1]/ d[1], x_b[2]/ d[2]]
theta_star = min(range(len(values)), key=values.__getitem__)
print(theta_star)
# x_1 exits the basis

1


/Users/garretttallman/opt/anaconda3/envs/isye6669/lib/python3.7/site-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


In [83]:
# iteration i = 2

i = 2
j = 3
p = 1
q = 4
k = 5

B = A[:, [i-1, j-1, k-1]]
B_inv = linalg.inv(B)
x_b = B_inv @ b
x_n = np.array([[0], [0]])
c_bar = c[p-1] - c[[i-1, j-1, k-1]].T @ B_inv @ A[:, p-1]
c_bar_2 = c[q-1] - c[[i-1, j-1, k-1]].T @ B_inv @ A[:, q-1]


print("B = ")
print(B)
print("\n B^-1 = ")
print(B_inv)
print("\n x_b")
print(x_b)
print("\n x_n")
print(x_n)
print("\n c_"+str(p)+"_bar = ")
print(c_bar)
print("\n c_"+str(q)+"_bar = ")
print(c_bar_2)

B = 
[[ 1  1  0]
 [ 1  0  0]
 [-1  0  1]]

 B^-1 = 
[[ 0.  1. -0.]
 [ 1. -1.  0.]
 [ 0.  1.  1.]]

 x_b
[[2.]
 [2.]
 [4.]]

 x_n
[[0]
 [0]]

 c_1_bar = 
[2.]

 c_4_bar = 
[-4.]


In [84]:
# x_4 enters the basis
d = -B_inv @ A[:, -1]
values = [x_b[0]/ d[0], x_b[1]/ d[1], x_b[2]/ d[2]]
theta_star = min(range(len(values)), key=values.__getitem__)
print(theta_star)
# x_2 exits the basis

1


/Users/garretttallman/opt/anaconda3/envs/isye6669/lib/python3.7/site-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


In [85]:
# iteration i = 3

i = 3
j = 4
p = 1
q = 2
k = 5

B = A[:, [i-1, j-1, k-1]]
B_inv = linalg.inv(B)
x_b = B_inv @ b
x_n = np.array([[0], [0]])
c_bar = c[p-1] - c[[i-1, j-1, k-1]].T @ B_inv @ A[:, p-1]
c_bar_2 = c[q-1] - c[[i-1, j-1, k-1]].T @ B_inv @ A[:, q-1]


print("B = ")
print(B)
print("\n B^-1 = ")
print(B_inv)
print("\n x_b")
print(x_b)
print("\n x_n")
print(x_n)
print("\n c_"+str(p)+"_bar = ")
print(c_bar)
print("\n c_"+str(q)+"_bar = ")
print(c_bar_2)

B = 
[[1 0 0]
 [0 1 0]
 [0 0 1]]

 B^-1 = 
[[ 1. -0. -0.]
 [ 0.  1. -0.]
 [ 0.  0.  1.]]

 x_b
[[4.]
 [2.]
 [2.]]

 x_n
[[0]
 [0]]

 c_1_bar = 
[-2.]

 c_2_bar = 
[4.]


In [86]:
# x_1 enters the basis
d = -B_inv @ A[:, p-1]
values = [x_b[0]/ d[0], x_b[1]/ d[1], x_b[2]/ d[2]]
theta_star = min(range(len(values)), key=values.__getitem__)
print(theta_star)
# x_5 exits the basis

0


In [87]:
# iteration i = 4

i = 1
j = 3
p = 2
q = 5
k = 4

B = A[:, [i-1, j-1, k-1]]
B_inv = linalg.inv(B)
x_b = B_inv @ b
x_n = np.array([[0], [0]])
c_bar = c[p-1] - c[[i-1, j-1, k-1]].T @ B_inv @ A[:, p-1]
c_bar_2 = c[q-1] - c[[i-1, j-1, k-1]].T @ B_inv @ A[:, q-1]


print("B = ")
print(B)
print("\n B^-1 = ")
print(B_inv)
print("\n x_b")
print(x_b)
print("\n x_n")
print(x_n)
print("\n c_"+str(p)+"_bar = ")
print(c_bar)
print("\n c_"+str(q)+"_bar = ")
print(c_bar_2)

B = 
[[ 1  1  0]
 [-1  0  1]
 [ 1  0  0]]

 B^-1 = 
[[ 0.  0.  1.]
 [ 1.  0. -1.]
 [ 0.  1.  1.]]

 x_b
[[2.]
 [2.]
 [4.]]

 x_n
[[0]
 [0]]

 c_2_bar = 
[2.]

 c_5_bar = 
[2.]


In [ ]:
#this is optimal