In [1]:
import cvxpy as cp
import cvxopt
import numpy as np
from scipy import linalg

### RMP Step1 

In [3]:
A = np.matrix([
    [10, 0, 0],
    [0, 7, 0],
    [0, 0, 5]
])
b = np.matrix([15, 30, 20]).T
x = cp.Variable((3,1))

rmp_obj = cp.Minimize(cp.sum(x))
rmp_constr = [
    A @ x == b,
    x >= 0
]

rmp_prob = cp.Problem(rmp_obj, rmp_constr)
rmp_prob_optimal_val = rmp_prob.solve()

In [5]:
#optimal solution
print("Optimal Solution:")
print("x1: {0}".format(x.value[0]))
print("x2: {0}".format(x.value[1]))
print("x3: {0}".format(x.value[2]))
print("---------------")

#optimal basis
print("Basis: \n{0}".format(A))
print("---------------")

#optimal basis inverse
print("Basis^-1: \n{0}".format(linalg.inv(A)))
print("---------------")

#dual problem solution
y_hat = -rmp_prob.constraints[0].dual_value
print("Y_hat: \n{0}".format(y_hat))

Optimal Solution:
x1: [1.5]
x2: [4.28571429]
x3: [4.]
---------------
Basis: 
[[10  0  0]
 [ 0  7  0]
 [ 0  0  5]]
---------------
Basis^-1: 
[[ 0.1        -0.         -0.        ]
 [ 0.          0.14285714 -0.        ]
 [ 0.          0.          0.2       ]]
---------------
Y_hat: 
[[0.1       ]
 [0.14285714]
 [0.2       ]]


### Pricing Step1

In [8]:
a = cp.Variable((3,1), integer=True)
w = np.matrix([7, 11, 16]).T

pricing_obj = cp.Maximize(y_hat.T @ a)
pricing_constr = [
    w.T @ a <= 80,
    a >= 0
]

pricing_prob = cp.Problem(pricing_obj, pricing_constr)
pricing_prob_optimal_value = pricing_prob.solve()

In [120]:
print("Optimal Solution Value: {0}".format(pricing_prob_optimal_value))
print("----------")
print("Optimal Solution:")
print("a1: {0}".format(a.value[0]))
print("a2: {0}".format(a.value[1]))
print("a3: {0}".format(a.value[2]))
print("---------------")
print("Minimum Reduced Cost: {0}".format(1-pricing_prob_optimal_value))

Optimal Solution Value: 1.034920635633645
----------
Optimal Solution:
a1: [2.]
a2: [6.]
a3: [0.]
---------------
Minimum Reduced Cost: -0.03492063563364489


#### Not optimal as the minimum reduced cost is < 0

##### Add the column [2, 6, 0].T

### RMP Step2

In [11]:
A = np.matrix([
    [10, 0, 0, 2],
    [0, 7, 0, 6],
    [0, 0, 5, 0]
])

b = np.matrix([15, 30, 20]).T
x = cp.Variable((4,1))

rmp_obj = cp.Minimize(cp.sum(x))
rmp_constr = [
    A @ x == b,
    x >= 0
]

rmp_prob = cp.Problem(rmp_obj, rmp_constr)
rmp_prob_optimal_val = rmp_prob.solve()

In [15]:
#optimal solution
print("Optimal Solution:")
print("x1: {0}".format(x.value[0]))
print("x2: {0}".format(x.value[1]))
print("x3: {0}".format(x.value[2]))
print("x4: {0}".format(x.value[3]))
print("---------------")

#optimal basis
print("Basis: \n{0}".format(np.delete(A, 1, 1)))
print("---------------")

#optimal basis inverse
print("Basis^-1: \n{0}".format(linalg.inv(np.delete(A, 1, 1))))
print("---------------")

#dual problem solution
y_hat = -rmp_prob.constraints[0].dual_value
print("Y_hat: \n{0}".format(y_hat))

Optimal Solution:
x1: [0.50000001]
x2: [3.34477147e-08]
x3: [4.]
x4: [4.99999996]
---------------
Basis: 
[[10  0  2]
 [ 0  0  6]
 [ 0  5  0]]
---------------
Basis^-1: 
[[ 0.1        -0.03333333 -0.        ]
 [ 0.         -0.          0.2       ]
 [ 0.          0.16666667  0.        ]]
---------------
Y_hat: 
[[0.1       ]
 [0.13333333]
 [0.2       ]]


### Pricing Step2

In [16]:
a = cp.Variable((3,1), integer=True)
w = np.matrix([7, 11, 16]).T

pricing_obj = cp.Maximize(y_hat.T @ a)
pricing_constr = [
    w.T @ a <= 80,
    a >= 0
]

pricing_prob = cp.Problem(pricing_obj, pricing_constr)
pricing_prob_optimal_value = pricing_prob.solve()

In [17]:
print("Optimal Solution Value: {0}".format(pricing_prob_optimal_value))
print("----------")
print("Optimal Solution:")
print("a1: {0}".format(a.value[0]))
print("a2: {0}".format(a.value[1]))
print("a3: {0}".format(a.value[2]))
print("---------------")
print("Minimum Reduced Cost: {0}".format(1-pricing_prob_optimal_value))

Optimal Solution Value: 1.0999999747289089
----------
Optimal Solution:
a1: [9.]
a2: [0.]
a3: [1.]
---------------
Minimum Reduced Cost: -0.09999997472890887


#### Not optimal as the minimum reduced cost is < 0

##### Add the column [9, 0, 1].T

### RMP Step3

In [18]:
A = np.matrix([
    [10, 0, 0, 2, 9],
    [0, 7, 0, 6, 0],
    [0, 0, 5, 0, 1]
])

b = np.matrix([15, 30, 20]).T
x = cp.Variable((5,1))

rmp_obj = cp.Minimize(cp.sum(x))
rmp_constr = [
    A @ x == b,
    x >= 0
]

rmp_prob = cp.Problem(rmp_obj, rmp_constr)
rmp_prob_optimal_val = rmp_prob.solve()

In [22]:
#optimal solution
print("Optimal Solution:")
print("x1: {0}".format(x.value[0]))
print("x2: {0}".format(x.value[1]))
print("x3: {0}".format(x.value[2]))
print("x4: {0}".format(x.value[3]))
print("x5: {0}".format(x.value[4]))
print("---------------")

#optimal basis
print("Basis: \n{0}".format(np.delete(A, [0,1], 1)))
print("---------------")

#optimal basis inverse
print("Basis^-1: \n{0}".format(linalg.inv(np.delete(A, [0,1], 1))))
print("---------------")

#dual problem solution
y_hat = -rmp_prob.constraints[0].dual_value
print("Y_hat: \n{0}".format(y_hat))

Optimal Solution:
x1: [1.62168819e-09]
x2: [6.98983982e-09]
x3: [3.88888889]
x4: [4.99999999]
x5: [0.55555556]
---------------
Basis: 
[[0 2 9]
 [0 6 0]
 [5 0 1]]
---------------
Basis^-1: 
[[-0.02222222  0.00740741  0.2       ]
 [-0.          0.16666667  0.        ]
 [ 0.11111111 -0.03703704  0.        ]]
---------------
Y_hat: 
[[0.08888889]
 [0.13703704]
 [0.2       ]]


### Pricing Step3

In [21]:
a = cp.Variable((3,1), integer=True)
w = np.matrix([7, 11, 16]).T

pricing_obj = cp.Maximize(y_hat.T @ a)
pricing_constr = [
    w.T @ a <= 80,
    a >= 0
]

pricing_prob = cp.Problem(pricing_obj, pricing_constr)
pricing_prob_optimal_value = pricing_prob.solve()

In [23]:
print("Optimal Solution Value: {0}".format(pricing_prob_optimal_value))
print("----------")
print("Optimal Solution:")
print("a1: {0}".format(a.value[0]))
print("a2: {0}".format(a.value[1]))
print("a3: {0}".format(a.value[2]))
print("---------------")
print("Minimum Reduced Cost: {0}".format(1-pricing_prob_optimal_value))

Optimal Solution Value: 1.00740740722685
----------
Optimal Solution:
a1: [6.]
a2: [2.]
a3: [1.]
---------------
Minimum Reduced Cost: -0.00740740722684996


#### Not optimal as the minimum reduced cost is < 0

##### Add the column [6, 2, 1].T

### RMP Step4

In [24]:
A = np.matrix([
    [10, 0, 0, 2, 9, 6],
    [0, 7, 0, 6, 0, 2],
    [0, 0, 5, 0, 1, 1]
])

b = np.matrix([15, 30, 20]).T
x = cp.Variable((6,1))

rmp_obj = cp.Minimize(cp.sum(x))
rmp_constr = [
    A @ x == b,
    x >= 0
]

rmp_prob = cp.Problem(rmp_obj, rmp_constr)
rmp_prob_optimal_val = rmp_prob.solve()

In [26]:
#optimal solution
print("Optimal Solution:")
print("x1: {0}".format(x.value[0]))
print("x2: {0}".format(x.value[1]))
print("x3: {0}".format(x.value[2]))
print("x4: {0}".format(x.value[3]))
print("x5: {0}".format(x.value[4]))
print("x6: {0}".format(x.value[5]))
print("---------------")

#optimal basis
print("Basis: \n{0}".format(np.delete(A, [0,1,4], 1)))
print("---------------")

#optimal basis inverse
print("Basis^-1: \n{0}".format(linalg.inv(np.delete(A, [0,1,4], 1))))
print("---------------")

#dual problem solution
y_hat = -rmp_prob.constraints[0].dual_value
print("Y_hat: \n{0}".format(y_hat))

Optimal Solution:
x1: [1.054794e-09]
x2: [4.75654238e-09]
x3: [3.8125]
x4: [4.6875]
x5: [2.71681735e-09]
x6: [0.9375]
---------------
Basis: 
[[0 2 6]
 [0 6 2]
 [5 0 1]]
---------------
Basis^-1: 
[[-0.0375  0.0125  0.2   ]
 [-0.0625  0.1875  0.    ]
 [ 0.1875 -0.0625  0.    ]]
---------------
Y_hat: 
[[0.0875]
 [0.1375]
 [0.2   ]]


### Pricing Step4

In [27]:
a = cp.Variable((3,1), integer=True)
w = np.matrix([7, 11, 16]).T

pricing_obj = cp.Maximize(y_hat.T @ a)
pricing_constr = [
    w.T @ a <= 80,
    a >= 0
]

pricing_prob = cp.Problem(pricing_obj, pricing_constr)
pricing_prob_optimal_value = pricing_prob.solve()

In [28]:
print("Optimal Solution Value: {0}".format(pricing_prob_optimal_value))
print("----------")
print("Optimal Solution:")
print("a1: {0}".format(a.value[0]))
print("a2: {0}".format(a.value[1]))
print("a3: {0}".format(a.value[2]))
print("---------------")
print("Minimum Reduced Cost: {0}".format(1-pricing_prob_optimal_value))

Optimal Solution Value: 1.0000000000570957
----------
Optimal Solution:
a1: [0.]
a2: [0.]
a3: [5.]
---------------
Minimum Reduced Cost: -5.709566153200285e-11


### Optimal

Optimal Solution:

In [29]:
x.value

array([[1.05479400e-09],
       [4.75654238e-09],
       [3.81250000e+00],
       [4.68750000e+00],
       [2.71681735e-09],
       [9.37499996e-01]])

Optimal Basis

In [30]:
#optimal basis
print("Basis: \n{0}".format(np.delete(A, [0,1,4], 1)))
print("---------------")

#optimal basis inverse
print("Basis^-1: \n{0}".format(linalg.inv(np.delete(A, [0,1,4], 1))))
print("---------------")

Basis: 
[[0 2 6]
 [0 6 2]
 [5 0 1]]
---------------
Basis^-1: 
[[-0.0375  0.0125  0.2   ]
 [-0.0625  0.1875  0.    ]
 [ 0.1875 -0.0625  0.    ]]
---------------


Optimal Objective Value

In [31]:
rmp_prob_optimal_val

9.437500000344182